server:
  port: 8443
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

spring:
  profiles:
    default: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_ddl
    username: root
    password: 1234
    mvc:
      view:
        prefix: /static/
        suffix: .html
  task:
    scheduling:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

  redis:
    host: localhost
    port: 6379

signup:
  Token: 7ae3c-cbf8f101ae-76a8becfb0-4002811a9c-5139f71893-80cdf25359-3073f96-a0da5eb6a35bd2-9638944694c19cc2a-178637ca9e8b227d-95374de6af-8d3447a452-58089826d4-b0ef3

logging:
  level:
    org.hibernate.sql: INFO

jwt:
  secretKey: 12ASDGKWE41246AS21ASD2412FSDSD1421PWQEIDVN213
  access:
    expiration: 3600000
    header: AccessToken
  refresh:
    expiration: 1209600000
    header: RefreshToken

imagePath:
  test:
#    dir: /Users/raccon/Documents/racconworld_data/
    dir : D:/image/ex/

  result:
    dir : D:/image/ex/
#    dir: /Users/raccon/Documents/racconworld_data/


