version: '3'

services:
  api-server:
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    ports:
      - "8080:8080"
    depends_on:
      - cache-server
      - database
    container_name: spring

  cache-server:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    container_name: redis

  database:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: test_ddl
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    container_name: mysql

networks:
  docker_world:
    external : true
