services:
  api-server:
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    platform: linux/arm64
    container_name: spring
    image: spring_racconworld
#    이미지 이름 지정
    restart: always
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_ddl?useSSL=true&verifyServerCertificate=true&requireSSL=true
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_ddl?useSSL=false
#      SPRING_DATASOURCE_USERNAME: "root"
#      SPRING_DATASOURCE_PASSWORD: "1234"
    ports:
      - "18666:8443"
    depends_on:
      - cache-server
      - database
    volumes:
      - /home/raccon/racconworld_data/img:/racconworld_data/img
    networks:
      - raccon_world

  cache-server:
    image: redis
    container_name: redis
    ports:
      - "18663:6379"
    networks:
      - raccon_world

  database:
    image: mysql:8.0.36
    container_name: mysql
    environment:
      MYSQL_DATABASE: test_ddl
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "18665:3306"
    volumes:
      - /home/raccon/racconworld_data/db:/var/lib/mysql
    networks:
      - raccon_world

  nginx:
    build:
      context: ../raccon_FE
      dockerfile: ./Dockerfile  # 위에서 만든 Dockerfile로 빌드
    container_name: nginx
    image: nginx_racconworld
    ports:
      - "80:80"
      - "443:443"  # HTTPS 포트도 열기
    depends_on:
      - api-server
    volumes:
      - /home/raccon/racconworld_data/img:/racconworld_data/img
    #    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt  # 인증서 파일을 저장할 경로
#      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - raccon_world
    env_file:
      - ../raccon_FE/.env.production

#  certbot:
#    image: certbot/certbot
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt
#      - /var/lib/letsencrypt:/var/lib/letsencrypt
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"
#    container_name: certbot
#    depends_on:
#      - nginx
#    networks:
#      - racconworld_world

volumes:
  mysql_data:

networks:
  raccon_world:
    name: raccon_world
    driver: bridge
    external: false

